name: SonarCloud Analysis
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
          pip install -e .

      - name: Run tests with coverage
        run: |
          pytest tests/ --cov=github_mcp --cov-report=xml --cov-report=term-missing

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=flexrpl
            -Dsonar.projectKey=fleXRPL_github_mcp
            -Dsonar.python.coverage.reportPaths=coverage.xml
            -Dsonar.sources=github_mcp
            -Dsonar.tests=tests
            -Dsonar.python.version=3
            -Dsonar.sourceEncoding=UTF-8
            -Dsonar.exclusions=docs/**,scripts/**
            -Dsonar.coverage.exclusions=tests/**,docs/**,scripts/**
            -Dsonar.python.xunit.reportPath=test-results.xml 